version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      args:
        - PHP_IMAGE_VERSION=${PHP_IMAGE_VERSION}
        - XDEBUG_VERSION=${XDEBUG_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - NPM_VERSION=${NPM_VERSION}
        - LARAVEL_VERSION=${LARAVEL_VERSION}
    container_name: "php7_3-mariadb5_5-php"
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      TZ: ${TIME_ZONE}
      LARAVEL_VERSION: ${LARAVEL_VERSION}
    tty: true
    volumes:
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini
      - ${XDEBUG_INI_PATH}:/usr/local/etc/php/conf.d/zz-xdebug.ini
      - ${PROJECT_PATH}:${PHP_PROJECT_ROOT}
    ports:
      - "800:8000"
      - "300:3000"
  db:
    build:
      context: ${DATABASE_BUILD_PATH}
      args:
        - DATABASE_IMAGE_VERSION=${DATABASE_IMAGE_VERSION}
    container_name: "php7_3-mariadb5_5-database"
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASS}
      TESTING_DATABASE: ${TESTING_DATABASE}
      TZ: ${TIME_ZONE}
    volumes:
      - ${DATABASE_CONF}:/etc/mysql/conf.d
      - ${DATABASE_DATA}:/var/lib/mysql
      - ${DATABASE_INIT}:/docker-entrypoint-initdb.d
    ports:
      - ${DATABASE_PORT}:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    container_name: "php7_3-mariadb5_5-phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${DATABASE_USER}
      - PMA_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
